menubar: false
toolbar:
  - bold italic | undo redo | image | link media
plugins:
  - image
  - link
  - media
  - autoresize
language: ko_KR
statusbar: false
relative_urls: false
media_alt_source: false
media_poster: false
media_live_embeds: true
autoresize_min_height: 350
autoresize_bottom_margin: 0
autoresize_overflow_padding: 0
